### ISSUE TITLE
Dataset format for relation extraction

### ISSUE THREAD

**Issue by wakeb98** [edchengg/GigaBERT#2]
please give me an example of relation extraction data

**Comment by edchengg** [comment]
`'''
data format:
{"tokens": ["We", "'", "ll", "have", "a", "couple", "of", "experts", "come", "out", ",", "so", "I", "'", "ll", "withhold", "my", "comments", "until", "then", "."], "arg1": {"id": "CNN_CF_20030303.1900.00-E28-170", "text": "We", "entity_type": "ORG", "mention_type": "PRO", "entity_subtype": "Media", "start": 0, "end": 1}, "arg2": {"id": "CNN_CF_20030303.1900.00-E84-167", "text": "couple", "entity_type": "PER", "mention_type": "PRO", "entity_subtype": "Group", "start": 5, "end": 6}, "label": "O", "sent_id": "CNN_CF_20030303.1900.00-2"}
'''`

**Comment by ahmedkotb98** [comment]
In this line    arg1 = examples['arg1'] and    
arg2 = examples['arg2'] you mean that your examples in the dataset contain arg1 and arg2 only?

**Comment by edchengg** [comment]
> 

one example

> In this line arg1 = examples['arg1'] and arg2 = examples['arg2'] you mean that your examples in the dataset contain arg1 and arg2 only?

one example.
the dataset contains multiple examples

**Comment by ahmedkotb98** [comment]
> one example
> 
> > In this line arg1 = examples['arg1'] and arg2 = examples['arg2'] you mean that your examples in the dataset contain arg1 and arg2 only?
> 
> one example. the dataset contains multiple examples

I mean that all examples consist of two args only?
This question is because in this function (process_relation_markers) you selected only arg1 and arg2

Second question: Do you use label studio as an annotation tool or something else?

**Comment by edchengg** [comment]
> > one example
> > > In this line arg1 = examples['arg1'] and arg2 = examples['arg2'] you mean that your examples in the dataset contain arg1 and arg2 only?
> > 
> > 
> > one example. the dataset contains multiple examples
> 
> I mean that all examples consist of two args only? This question is because in this function (process_relation_markers) you selected only arg1 and arg2
> 
> Second question: Do you use label studio as an annotation tool or something else?

1. yes
2. no, its ACE2005 dataset(https://catalog.ldc.upenn.edu/LDC2006T06). I can't share it without a license.

**Comment by wakeb98** [comment]
you give me one example above now i want to give me an example of two examples of relation dataset
