### ISSUE TITLE
the Format of (train-ar-relation.json)

### ISSUE THREAD

**Issue by Help100** [edchengg/GigaBERT#4]
IN arabic_relation
Please can you give me the format of this file JSON (Just 2 examples in the file ((the start and end of the file JSON )))? 

![52](https://user-images.githubusercontent.com/110594757/182794815-2f252466-e286-495a-9fab-6baa40de4564.PNG)

Then why these brackets are there in only the train path (not in the other paths)? 
![ff](https://user-images.githubusercontent.com/110594757/182796105-4aa83869-209d-444d-9b13-27b208524c0e.PNG)

**Comment by Help100** [comment]
when I try this example (({"tokens": ["We", "'", "ll", "have", "a", "couple", "of", "experts", "come", "out", ",", "so", "I", "'", "ll", "withhold", "my", "comments", "until", "then", "."], "arg1": {"id": "CNN_CF_20030303.1900.00-E28-170", "text": "We", "entity_type": "ORG", "mention_type": "PRO", "entity_subtype": "Media", "start": 0, "end": 1}, "arg2": {"id": "CNN_CF_20030303.1900.00-E84-167", "text": "couple", "entity_type": "PER", "mention_type": "PRO", "entity_subtype": "Group", "start": 5, "end": 6}, "label": "O", "sent_id": "CNN_CF_20030303.1900.00-2"}
))

It works well, and no errors. 

But How can I add an N  number of examples ??  (The format of JSON)
and The code run in (map function). 
in these lines :
datasets_relation = dataset.map(process_relation_markers)
tokenized_datasets = datasets_relation.map(
    tokenize_function,
    batched=True,
)

I am trying to train the model. 
Thank you.

**Comment by edchengg** [comment]
each line is a dictionary. it works with jsonl. but the file name needs to be "*.json"
